# Generated by Django 4.2 on 2025-03-21 18:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('party_size', models.PositiveIntegerField()),
                ('seating_type', models.CharField(choices=[('TABLE', 'Table Seating'), ('COUNTER', 'Counter Seating')], max_length=10)),
                ('status', models.CharField(choices=[('CONFIRMED', 'Booking Confirmed'), ('CANCELLED', 'Booking Cancelled'), ('AWAITING', 'Awaiting Response'), ('DUPLICATE', 'Multiple Bookings - Contact')], default='AWAITING', max_length=20)),
                ('cancel_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
    ]
